name: "吾爱破解签到"

on:
  workflow_dispatch:
  schedule:
    # 每天国际时间 12:40 运行一次, 中国时间 20:40
    - cron: '40 12 * * *'
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: '代码检查'
        uses: actions/checkout@v2
      - name: '初始化Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: 缓存 Chromium
        uses: actions/cache@v2
        with:
          path: ${{ runner.cacheDirectory }}/.local/share/pyppeteer/local-chromium/
          key: ${{ runner.os }}-chromium
      - name: '安装依赖包'
        run: |
          pip install --upgrade pip
          python -m pip install --upgrade requests
          pip install beautifulsoup4
          pip install pyppeteer
          python -m pip install pyppeteer
      - name: '开始签到'
        env:
          PYPPETEER_EXECUTABLE_PATH: ${{ runner.toolcache }}/Cache Chromium/linux/chrome-90.0.4430.85/chrome
          52PjCookie: ${{ secrets.PjCookie }}
          PushToken: ${{ secrets.PushToken }}
          
        run: python main.py
